export const SHOW_AUTHENTICATE_MODAL = 'SHOW_AUTHENTICATE_MODAL';
export const HIDE_AUTHENTICATE_MODAL = 'HIDE_AUTHENTICATE_MODAL';
export const SESSION_REQUEST_TOKEN_MAIL = 'SESSION_REQUEST_TOKEN_MAIL';
export const SESSION_GOOGLE_TOKEN_LOGIN = 'SESSION_GOOGLE_TOKEN_LOGIN';
export const SESSION_FACEBOOK_TOKEN_LOGIN = 'SESSION_FACEBOOK_TOKEN_LOGIN';
export const SESSION_LOGIN_WITH_TOKEN = 'SESSION_LOGIN_WITH_TOKEN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';

// TODO DELETE THIS FILE