export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const SESSION_LOGIN_CREDENTIALS = 'SESSION_LOGIN_CREDENTIALS';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
