export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const SESSION_REQUEST_TOKEN_MAIL = 'SESSION_REQUEST_TOKEN_MAIL';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
