export const LOADING_INCREMENT = 'LOADING_INCREMENT';
export const LOADING_DECREMENT = 'LOADING_DECREMENT';
export const SESSION_LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SESSION_LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SESSION_LOGIN_PENDING = 'LOGIN_PENDING';
export const SESSION_LOGOUT = 'LOGOUT';
